apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: desafio-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio-api
  template:
    metadata:
      labels:
        app: desafio-api
    spec:
      containers:
        - name: api
          image: desafio-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "desafio-db-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              value: "desafio_db"
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: desafio-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
