apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: desafio-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio-db
  template:
    metadata:
      labels:
        app: desafio-db
    spec:
      containers:
        - name: db
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: root_password
            - name: MYSQL_DATABASE
              value: "desafio_db"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: desafio-db-service
  namespace: desafio-db
spec:
  selector:
    app: desafio-db
  ports:
    - protocol: TCP
      port: 3306
  clusterIP: None
