apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: desafio-api
spec:
  selector:
    app: desafio-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
